disabled_rules:
  - trailing_comma
  - todo
  - file_length

opt_in_rules:
  - array_init
  - closure_spacing
  - empty_count
  - explicit_init
  - first_where
  - implicit_return
  - multiline_arguments
  - multiline_parameters
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

line_length:
  warning: 120
  error: 150

file_length:
  warning: 400
  error: 500

type_body_length:
  warning: 250
  error: 350

function_body_length:
  warning: 40
  error: 60

type_name:
  min_length: 3
  max_length: 50

variable_name:
  min_length: 2
  max_length: 50

excluded:
  - DerivedData
  - .build
  - Pods

reporter: "xcode"
