# SwiftLint Configuration for iOS Template

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - DerivedData
  - Pods
  - Carthage
  - .swiftpm
  - "**/Generated"

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - trailing_whitespace
  - force_cast
  - force_try

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
    error: 5
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ID
    - x
    - y
    - z
    - r
    - g
    - b
    - a
    - i
    - j
    - k
    - db
    - vc
    - to
    - at
    - me

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - ID
    - URL
    - API

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  # Prefer using @Dependency over direct initialization
  use_dependency_macro:
    name: "Use @Dependency Macro"
    regex: "var\\s+\\w+\\s*=\\s*\\w+\\(\\)"
    message: "Use @Dependency macro for dependencies instead of direct initialization"
    severity: warning

  # Avoid force unwrapping
  no_force_unwrapping:
    name: "No Force Unwrapping"
    regex: "\\!(?!\\=)"
    match_kinds: identifier
    message: "Avoid using force unwrapping (!)"
    severity: warning

  # Prefer using guard over if let for early returns
  prefer_guard:
    name: "Prefer Guard"
    regex: "if\\s+let\\s+\\w+\\s*=\\s*.+\\s*\\{[\\s\\S]*return"
    message: "Use guard for early returns instead of if let"
    severity: warning

  # No print statements (use logger)
  no_print:
    name: "No Print Statements"
    regex: "\\bprint\\("
    match_kinds:
      - identifier
    message: "Use Logger instead of print()"
    severity: warning
    excluded: ".*/Tests/.*"

  # ViewStore binding should use proper syntax
  proper_viewstore_binding:
    name: "Proper ViewStore Binding"
    regex: "ViewStore.*binding:"
    message: "Use @Bindable or proper binding syntax with ViewStore"
    severity: info

# Reporter
reporter: "xcode"

# Warnings as errors (for CI)
# strict: true

# Number of violations before reporting
warning_threshold: 10
error_threshold: 50

# Allow SwiftLint to analyze generated code
# analyze_generated_code: false
